# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(
                    auto_now=True, verbose_name='Date Modified')),
                ('notification_type', models.CharField(
                    choices=[('1', 'Health Facility Catchment Finished'),
                             ('2', 'Weekly Dashboard Update'),
                             ('3', 'SO Daily Form Completed'),
                             ('4', 'GPS OFF'),
                             ('5', 'User Distance')],
                    max_length=1, verbose_name='Notification Type')),
                ('get_data',
                 django.contrib.postgres.fields.jsonb.JSONField(
                    default={}, verbose_name='GET data')),
                ('post_data',
                 django.contrib.postgres.fields.jsonb.JSONField(
                    default={}, verbose_name='POST data')),
                ('success', models.BooleanField(default=False,
                                                verbose_name='Success')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
            },
        ),
    ]
