# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hhcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmid', models.IntegerField()),
                ('y', models.FloatField()),
                ('x3', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('shape_length', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='OsmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmid', models.IntegerField()),
                ('target_area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=3)),
                ('shape_area', models.FloatField()),
                ('shape_length', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'osm_data',
            },
        ),
        migrations.CreateModel(
            name='SprayPointView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprayable_structure', models.CharField(max_length=10)),
                ('was_sprayed', models.CharField(max_length=10)),
                ('irs_card_num', models.CharField(max_length=10)),
                ('osmstructure', models.CharField(max_length=50)),
                ('unsprayed_reason', models.CharField(max_length=50)),
                ('location_code', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('team_leader_id', models.IntegerField()),
                ('team_leader_code', models.CharField(max_length=50)),
                ('team_leader_name', models.CharField(max_length=255)),
                ('spray_operator_id', models.IntegerField()),
                ('sprayoperator_code', models.CharField(max_length=10)),
                ('spray_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'main_spray_point_view',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(db_index=1, max_length=255)),
                ('houses', models.IntegerField(db_index=1)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('code', models.CharField(db_index=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('bgeom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdsBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_households', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=1, max_length=255)),
                ('code', models.CharField(db_index=1, max_length=50, unique=True)),
                ('level', models.CharField(db_index=1, max_length=50)),
                ('structures', models.PositiveIntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
        migrations.CreateModel(
            name='MatchedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmpk', models.IntegerField(unique=True)),
                ('osmid', models.IntegerField()),
                ('target_area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=3)),
                ('shape_area', models.FloatField()),
                ('shape_length', models.FloatField()),
                ('y', models.FloatField()),
                ('x3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SprayDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField(unique=True)),
                ('spray_date', models.DateField(db_index=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326)),
                ('bgeom', django.contrib.gis.db.models.fields.GeometryField(db_index=True, null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SprayOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(db_index=1, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
                ('sprayday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SprayDay')),
            ],
        ),
        migrations.CreateModel(
            name='TargetArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetid', models.CharField(db_index=1, max_length=50)),
                ('targeted', models.IntegerField(db_index=1, default=1)),
                ('district_name', models.CharField(max_length=254)),
                ('houses', models.IntegerField(db_index=1)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(db_index=1, max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
        migrations.AddField(
            model_name='sprayoperator',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeader'),
        ),
        migrations.AddField(
            model_name='sprayday',
            name='spray_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SprayOperator'),
        ),
        migrations.AddField(
            model_name='sprayday',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeader'),
        ),
        migrations.AddField(
            model_name='householdsbuffer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
        migrations.AddField(
            model_name='household',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='spraypoint',
            unique_together=set([('data_id', 'location')]),
        ),
    ]
