# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('code', 'rank', 'level', 'parent')]),
        ),
    ]
