# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('code', 'rank', 'level')]),
        ),
    ]
