# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160825_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='homesteads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
