# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 06:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160830_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
