# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160906_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayoperatordailysummary',
            name='spray_form_id',
            field=models.CharField(max_length=50),
        ),
    ]
