# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dataentryclerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentryclerk',
            name='location',
        ),
        migrations.DeleteModel(
            name='DataEntryClerk',
        ),
    ]
