# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160908_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='average_spray_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='data_quality_check',
            field=models.BooleanField(default=False),
        ),
    ]
