# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160908_0756'),
        ('main', '0004_auto_20160908_0740'),
    ]

    operations = [
    ]
