# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directlyobservedsprayingform',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sprayoperatordailysummary',
            name='data',
        ),
    ]
