# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='directlyobservedsprayingform',
            name='submission_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprayoperatordailysummary',
            name='submission_id',
            field=models.IntegerField(default=0),
        ),
    ]
