# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160908_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(unique=True)),
                ('version', models.IntegerField()),
                ('changeset', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.IntegerField(unique=True)),
                ('action', models.CharField(max_length=20)),
                ('version', models.IntegerField()),
                ('changeset', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('nd_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WayTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Way')),
            ],
        ),
    ]
