# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160916_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(db_index=1, max_length=255)),
                ('data_quality_check', models.BooleanField(default=False)),
                ('average_spray_quality_score', models.FloatField(default=0.0)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
    ]
