# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teamleaderassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayoperator',
            name='team_leader_assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeaderAssistant'),
        ),
    ]
