# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160914_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waytag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='waytag',
            name='way',
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='way',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='WayTag',
        ),
    ]
