# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 09:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160914_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
