# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160914_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='nd_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
