# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160914_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
