# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_spray_point_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayoperatordailysummary',
            name='submission_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
