# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160918_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directlyobservedsprayingform',
            name='submission_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
