# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160918_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='num_of_spray_areas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
