# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_location_num_of_spray_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='was_sprayed',
            field=models.BooleanField(default=False),
        ),
    ]
