# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160914_0934'),
        ('main', '0019_location_num_of_spray_areas'),
    ]

    operations = [
    ]
