# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 07:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.AddField(
            model_name='node',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='way_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
