# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_spraydaydistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='osmid',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
