# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sprayday_osmid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spraydaydistrict',
            unique_together=set([('location', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='spraydayhealthcenterlocation',
            unique_together=set([('location', 'content_object')]),
        ),
    ]
