# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20160924_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_district', to='main.Location'),
        ),
        migrations.AddField(
            model_name='sprayday',
            name='rhc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_rhc', to='main.Location'),
        ),
    ]
