# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161112_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
