# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_location_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sprayed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
