# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_location_sprayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lft',
            field=models.PositiveIntegerField(db_index=True,
                                              default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='mptt_level',
            field=models.PositiveIntegerField(db_index=True,
                                              default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='rght',
            field=models.PositiveIntegerField(db_index=True,
                                              default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True,
                                              default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='main.Location'),
        ),
    ]
