# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_location_sprayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='is_new_structure',
            field=models.BooleanField(default=False),
        ),
    ]
