# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_location_pre_season_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprayday',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
