# -*- coding: utf-8 -*-
"""
sprayable field migration module.
"""
# Generated by Django 1.11.5 on 2017-10-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the field `sprayable` to SprayDay.
    """

    dependencies = [
        ('main', '0030_auto_20171010_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayday',
            name='sprayable',
            field=models.BooleanField(default=False),
        ),
    ]
