# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_sprayday_sprayable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleaderassistant',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeader'),
        ),
    ]
