# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 09:48
from __future__ import unicode_literals

from django.db import migrations

from mspray.apps.main.utils import remove_duplicate_sprayoperatordailysummary


def remove_duplicates(apps, schema_editor):
    remove_duplicate_sprayoperatordailysummary()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_teamleaderassistant_team_leader'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
