# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main',
         '0033_remove_duplicate_sprayoperatordailysummary_spray_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayoperatordailysummary',
            name='spray_form_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
