# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_make_sprayoperatordailysummary_spray_form_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprayformid', models.CharField(max_length=20)),
                ('found', models.IntegerField(default=0)),
                ('sprayed', models.IntegerField(default=0)),
                ('refused', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('spray_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('data_quality_check', models.BooleanField()),
                ('reported_found', models.IntegerField(default=0)),
                ('reported_sprayed', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('spray_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SprayOperator')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeader')),
                ('team_leader_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TeamLeaderAssistant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performancereport',
            unique_together=set([('spray_operator', 'sprayformid')]),
        ),
    ]
