# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20171112_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereport',
            name='not_eligible',
            field=models.IntegerField(default=0),
        ),
    ]
