# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_performancereport_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('visited', models.PositiveIntegerField(default=0)),
                ('sprayed', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set([('week_number', 'location')]),
        ),
    ]
