# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20171208_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='structures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
