# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20171209_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='target',
            field=models.BooleanField(default=True),
        ),
    ]
