# Generated by Django 2.1.1 on 2018-09-25 01:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0041_location_target")]

    operations = [
        migrations.AlterField(
            model_name="directlyobservedsprayingform",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="household",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="sprayday",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="sprayoperatordailysummary",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
