# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 19:10
from __future__ import unicode_literals

from django.db import migrations


SPRAY_POINT_VIEW = """
CREATE MATERIALIZED VIEW main_spray_point_view AS (SELECT DISTINCT ON ("main_sprayday"."id") "main_sprayday"."id", (data->>'sprayable_structure') AS "sprayable_structure",
                                          (data->>'sprayable/unsprayed/reason') AS "unsprayed_reason",
                                          (data->>'sprayable/was_sprayed') AS "was_sprayed",
                                          (data->>'sprayable/irs_card_num') AS "irs_card_num",
                                          (data->>'osmstructure') AS "osmstructure",
                                          (data->>'sprayformid') AS "sprayformid",
                                          "main_sprayday"."location_id" AS location_id,
                                          "main_location"."code" AS location_code,
                                          T3."id" AS district_id,
                                          T3."code" AS district_code,
                                          "main_sprayday"."team_leader_id",
                                          "main_teamleader"."code" AS team_leader_code,
                                          "main_teamleader"."name" AS team_leader_name,
                                          "main_teamleaderassistant"."code" AS team_leader_assistant_code,
                                          "main_sprayday"."spray_operator_id",
                                          "main_sprayoperator"."code" AS sprayoperator_code,
                                          "main_sprayday"."spray_date",
                                          "main_sprayday"."start_time",
                                          "main_sprayday"."end_time"
FROM "main_sprayday"
LEFT OUTER JOIN "main_location" ON ("main_sprayday"."location_id" = "main_location"."id")
LEFT OUTER JOIN "main_location" T3 ON ("main_location"."parent_id" = T3."id")
LEFT OUTER JOIN "main_teamleader" ON ("main_sprayday"."team_leader_id" = "main_teamleader"."id")
LEFT OUTER JOIN "main_teamleaderassistant" ON ("main_sprayday"."team_leader_assistant_id" = "main_teamleaderassistant"."id")
LEFT OUTER JOIN "main_sprayoperator" ON ("main_sprayday"."spray_operator_id" = "main_sprayoperator"."id")
WHERE "main_sprayday"."id" IN
    (SELECT U0."sprayday_id"
     FROM "main_spraypoint" U0));
"""  # noqa


def forwards(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute('DROP MATERIALIZED VIEW main_spray_point_view;')


def backwards(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute(SPRAY_POINT_VIEW)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20180925_0121'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
