# Generated by Django 2.1.1 on 2018-09-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_drop_spray_point_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(db_index=1, max_length=10),
        ),
    ]
