# Generated by Django 2.1.1 on 2018-09-26 19:23

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_add_spray_point_materialized_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitizationVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_sensitized', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sv_districts', to='main.Location')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sv_health_facilities', to='main.Location')),
                ('spray_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sv_spray_areas', to='main.Location')),
            ],
        ),
    ]
