# Generated by Django 2.1.1 on 2018-09-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_sensitizationvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitizationvisit',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sv_households', to='main.Household'),
        ),
    ]
