# Generated by Django 2.1.1 on 2018-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_location_is_sensitized'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_mobilised',
            field=models.BooleanField(null=True),
        ),
    ]
