# Generated by Django 2.1.1 on 2018-10-01 11:05

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0049_location_is_mobilised")]

    operations = [
        migrations.CreateModel(
            name="Mobilisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.PositiveIntegerField(unique=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                ("is_mobilised", models.BooleanField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mb_districts",
                        to="main.Location",
                    ),
                ),
                (
                    "health_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mb_health_facilities",
                        to="main.Location",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_households",
                        to="main.Household",
                    ),
                ),
                (
                    "spray_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mb_spray_areas",
                        to="main.Location",
                    ),
                ),
            ],
        )
    ]
