# Generated by Django 2.1.1 on 2018-10-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_mobilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='visited',
            field=models.BooleanField(null=True),
        ),
    ]
