# Generated by Django 2.1.1 on 2018-10-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0051_household_visited")]

    operations = [
        migrations.AddField(
            model_name="sprayday",
            name="household",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Household",
            ),
        )
    ]
