# Generated by Django 2.1.1 on 2018-10-15 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("main", "0052_sprayday_household")]

    operations = [
        migrations.AddField(
            model_name="household",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="household",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
