# Generated by Django 2.1.2 on 2018-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20181015_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='sprayable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='visited',
            field=models.NullBooleanField(),
        ),
    ]
