# Generated by Django 2.1.3 on 2018-11-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='priority',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
