# Generated by Django 2.1.3 on 2018-11-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0056_location_priority")]

    operations = [
        migrations.AddField(
            model_name="household",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houshold_district_set",
                to="main.Location",
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="rhc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="household_rhc_set",
                to="main.Location",
            ),
        ),
    ]
