# Generated by Django 2.1.3 on 2018-11-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0057_auto_20181121_0734")]

    operations = [
        migrations.AddField(
            model_name="sprayoperator",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sop_district",
                to="main.Location",
            ),
        )
    ]
