# Generated by Django 2.1.3 on 2018-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0059_sprayoperator_rhc")]

    operations = [
        migrations.AlterField(
            model_name="performancereport",
            name="data_quality_check",
            field=models.BooleanField(null=True),
        )
    ]
