# Generated by Django 2.1.3 on 2018-12-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0060_auto_20181208_1131")]

    operations = [
        migrations.AlterField(
            model_name="performancereport",
            name="team_leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.TeamLeader",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="team_leader_assistant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.TeamLeaderAssistant",
            ),
        ),
    ]
