# Generated by Django 2.1.3 on 2018-12-08 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20181208_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereport',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
