# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-09 20:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0040_auto_20171209_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=10)),
                ('collection_method', models.CharField(choices=[('CDC Light Trap', 'CDC Light Trap'), ('Prokopack', 'Prokopack')], max_length=20)),
                ('sample_date', models.DateField()),
                ('visit', models.PositiveSmallIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_samples', to='main.Location')),
                ('spray_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spray_area_samples', to='main.Location')),
            ],
        ),
    ]
