# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='submission_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
