# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-10 15:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_sample_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='bgeom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
